### PR TITLE
Copy some company-mode code from Intero

### PR DESCRIPTION
**Pull request by puffnfresh**
Does some stuff if I manually call company-dante while writing some code.

---

Can someone test this out? I'm wondering if the Haskell Spacemacs layer doesn't have Company configured correctly.

### CODE REVIEW

**Comment by puffnfresh** [comment]
Looks like I can get it to do something useful by adding the following:

```elisp
(require 'company)
(add-to-list (make-local-variable 'company-backends) 'company-dante)
(company-mode)
```

**Comment by jyp** [comment]
Could you add the setup instructions to the readme?

**Comment by puffnfresh** [comment]
@jyp I don't think they should be instructions. I think Dante should try to configure company mode, if it's available, like Intero does.

**Comment by jyp** [comment]
Alright; how about putting

(add-to-list (make-local-variable 'company-backends) 'company-dante)


in an eval-after-load block?

**Comment by jyp** [comment]
I'm merging this so it won't get lost. Most likely I wont be using completion so please advise with further pull requests on how to improve any pending issue.

**Pull request merged**
