### PR TITLE
Improvements to launching GHCi and bug fixes

### PR DESCRIPTION
**Pull request by drvink**
See commit messages for details.

### CODE REVIEW

**Comment by drvink** [comment]
Right now dante fails to start if a `stack.yaml` file is present, but stack can't be executed. This PR makes dante try nix (if there's a nix file) and finally `cabal repl` before giving up. An option is also provided to not try stack first, because who the hell wants to use stack?

Please let me know if there's any issues.

**Comment by jyp** [comment]
Sorry I did not see the PR earlier. I'll look into it in the coming days.

**Comment by jyp** [comment]
I've merged this, but I'm not too happy with the complexity of the logic behind the selection of environments. Indeed, running GHCi is complicated enough, I want to have the simplest logic to choose what to run.

How can we simplify this to the maximum? 
Suggestions:
- get rid of the unpreferred list and let the user customize dante-repl-command-line-methods directly
- not try all the possible backend, but only pick the first "statically" matching choice (again the user should customize dante-repl-command-line-methods on a per-project basis to match their liking).

I'll probably apply those unless you scream :)

**Comment by drvink** [comment]
No problem, I'm glad you saw it now. :)

Your suggestion sounds good to me--having it be per-project makes sense (I guess the user would do this via directory-local variables, perhaps?)

**Comment by jyp** [comment]
Great, I'll do some simplifications when I get the chance.

And yes, directory-local variables is the way to go.

**Pull request merged**
